name = "manifest"
main = "src/index.ts"
compatibility_date = "2024-10-12"
compatibility_flags = [ "nodejs_compat" ]
account_id = "c774cc0e6926f8bafd6bf80498254e91"
workers_dev = true
send_metrics = false
minify = true

kv_namespaces = [
  { binding = "INTRO_SKIPPER_JSON", id = "61215c51799a4de59f0a33a8b7aecb0e", preview_id="49c07e5b68074443b940de893d58a997" }
]

routes = [
  { pattern = "manifest.intro-skipper.org", custom_domain = true },
  { pattern = "intro-skipper.org", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1